create table caja (saldo_final float(53) not null, saldo_inicial float(53) not null, fecha datetime(6), id bigint not null auto_increment, id_usuario bigint, estado enum ('ABIERTA','CERRADA') not null, primary key (id)) engine=InnoDB;
create table carrito (cantidad INT NOT NULL DEFAULT 1 not null, id bigint not null auto_increment, id_producto bigint not null, id_usuario bigint not null, primary key (id)) engine=InnoDB;
create table categorias (id bigint not null auto_increment, nombre varchar(20) not null, primary key (id)) engine=InnoDB;
create table clientes (id bigint not null auto_increment, usuario_id bigint, celular varchar(20) not null, nomb_ape varchar(60) not null, nomb_usu varchar(60) not null, contrasena varchar(71) not null, correo varchar(120) not null, direccion varchar(120) not null, primary key (id)) engine=InnoDB;
create table compras (activo boolean default true, total decimal(10,2), fecha_hora datetime(6), id bigint not null auto_increment, id_caja bigint not null, id_proveedor bigint not null, id_usuario bigint not null, descripcion varchar(255) not null, primary key (id)) engine=InnoDB;
create table consultas (activo boolean default 0, id bigint not null auto_increment, celular varchar(15) not null, nom_ape varchar(50) not null, correo varchar(120) not null, mensaje varchar(500) not null, rese�a varchar(500), primary key (id)) engine=InnoDB;
create table cursos (precio decimal(38,2) not null, id bigint not null auto_increment, id_receta bigint not null, nombre_curso varchar(60) not null, descripcion varchar(500) not null, link_video varchar(500) not null, primary key (id)) engine=InnoDB;
create table detalle_compra (cantidad integer not null check (cantidad>=1), precio_unitario decimal(38,2) not null, compra_id bigint not null, id bigint not null auto_increment, ingrediente_id bigint not null, producto_id bigint not null, primary key (id)) engine=InnoDB;
create table detalle_factura (cantidad integer not null, precio_unitario decimal(38,2) not null, id bigint not null auto_increment, id_factura bigint, id_producto bigint not null, primary key (id)) engine=InnoDB;
create table detalle_venta (cantidad integer not null, precio_unitario decimal(38,2) not null, subtotal decimal(38,2) not null, id bigint not null auto_increment, id_venta bigint not null, item_id bigint not null, tipo_item enum ('CURSO','PRODUCTO') not null, primary key (id)) engine=InnoDB;
create table facturas (activo boolean default 1, fecha_pedido datetime(6) not null, id bigint not null auto_increment, id_caja bigint, id_cliente bigint, metodo_pago varchar(255) not null, numero_factura varchar(255) not null, primary key (id)) engine=InnoDB;
create table inscripciones (fecha_inscripcion datetime(6), id bigint not null auto_increment, id_cliente bigint, id_curso bigint, primary key (id)) engine=InnoDB;
create table inventario (activo boolean default true, cantidad integer not null check (cantidad>=1), fecha_ingreso date not null, fecha_vencimiento date not null, precio decimal(10,2) not null, id bigint not null auto_increment, id_proveedor bigint not null, id_usuario bigint, nombre_ingrediente varchar(50) not null, unidad_medida varchar(100) not null, primary key (id)) engine=InnoDB;
create table movimientos_caja (monto decimal(38,2) not null, monto_double float(53) not null, fecha datetime(6) not null, id bigint not null auto_increment, id_caja bigint, id_compra bigint, id_factura bigint, id_usuario bigint, id_venta bigint, tipo varchar(10) not null, descripcion varchar(255), tipo_operacion enum ('EGRESO','INGRESO') not null, primary key (id)) engine=InnoDB;
create table permisos (id bigint not null auto_increment, nombre varchar(20) not null, descripcion varchar(255), primary key (id)) engine=InnoDB;
create table persistent_logins (last_used TIMESTAMP not null, series varchar(64) not null, token varchar(64) not null, username varchar(64) not null, primary key (series)) engine=InnoDB;
create table productos (activo boolean default 1, precio decimal(10, 2) default 0.00 not null, stock integer not null, id bigint not null auto_increment, id_categoria bigint not null, descripcion varchar(65) not null, lnk_img varchar(1000), primary key (id)) engine=InnoDB;
create table proveedores (activo boolean default true, id bigint not null auto_increment, telefono varchar(50) not null, contacto varchar(100) not null, nombre varchar(100) not null, email varchar(120) not null, direccion varchar(255) not null, primary key (id)) engine=InnoDB;
create table recetas (id bigint not null auto_increment, tiempo varchar(50) not null, nombre_receta varchar(100) not null, ingredientes varchar(250) not null, descripcion varchar(500) not null, imagen_link varchar(500) not null, pasos varchar(500) not null, primary key (id)) engine=InnoDB;
create table usuarios (activo boolean default 1, fecha_creacion datetime(6), id bigint not null auto_increment, id_permiso bigint, nomb_usu varchar(30) not null, clave varchar(71), email varchar(100) not null, primary key (id)) engine=InnoDB;
create table ventas (total decimal(38,2) not null, fecha_venta datetime(6) not null, id bigint not null auto_increment, id_cliente bigint, id_usuario bigint, metodo_pago varchar(255) not null, estado enum ('CANCELADA','COMPLETADA','PENDIENTE') not null, primary key (id)) engine=InnoDB;
alter table clientes add constraint UK96x1n5ut15ns1xhkm87y7qhnd unique (usuario_id);
alter table permisos add constraint UKmd9j2tw7h6dxprrypo0itpnyp unique (nombre);
alter table usuarios add constraint UKkfsp0s1tflm1cwlj8idhqsad0 unique (email);
alter table caja add constraint FKl8a22u96putem18rfxghkf22e foreign key (id_usuario) references usuarios (id);
alter table carrito add constraint FKq3rb2epiiobwcybsy6p15400a foreign key (id_producto) references productos (id);
alter table carrito add constraint FKkg5h8ejijsgwfr68aoggh4l8m foreign key (id_usuario) references usuarios (id);
alter table clientes add constraint FKk6iwsq3kts1bblivkjy6epajx foreign key (usuario_id) references usuarios (id);
alter table compras add constraint FKt0q1m9m97yen174eeidlk4rvr foreign key (id_caja) references caja (id);
alter table compras add constraint FKkypgd762ocsq30thp7sxxhd20 foreign key (id_proveedor) references proveedores (id);
alter table compras add constraint FKsfjim1druo8tc28uvbb799tc4 foreign key (id_usuario) references usuarios (id);
alter table cursos add constraint FKsayxlccxcxlfupjyufn97lgxh foreign key (id_receta) references recetas (id);
alter table detalle_compra add constraint FKh4rhi4dqyjuo23ir3yxmqu031 foreign key (compra_id) references compras (id);
alter table detalle_compra add constraint FKnmotdkmjyoqqur9oakf679lof foreign key (ingrediente_id) references inventario (id);
alter table detalle_compra add constraint FK8b0jvrk3kn8aq74xxjjhjoy95 foreign key (producto_id) references productos (id);
alter table detalle_factura add constraint FKdottb80mhiedtx8j8jyqewx5n foreign key (id_factura) references facturas (id);
alter table detalle_factura add constraint FK8n490j4f7licrmb4jbk5mgmsp foreign key (id_producto) references productos (id);
alter table detalle_venta add constraint FKgds50vmwbs8lxoti80iekstyi foreign key (id_venta) references ventas (id);
alter table facturas add constraint FK9lwy7vhbg64445eqxry7lajho foreign key (id_caja) references caja (id);
alter table facturas add constraint FKp2ab9l9b5y3b0pv1ag1hfiun7 foreign key (id_cliente) references clientes (id);
alter table inscripciones add constraint FKj5lol6pkkcg52wxriulxiw16x foreign key (id_cliente) references clientes (id);
alter table inscripciones add constraint FKmyps0lutv0v9xqttbepwe14jt foreign key (id_curso) references cursos (id);
alter table inventario add constraint FKfaw3xt1j7iktfcj4kdl8brj3 foreign key (id_proveedor) references proveedores (id);
alter table inventario add constraint FKe91hgha9wf9oy7by5a25bnwp3 foreign key (id_usuario) references usuarios (id);
alter table movimientos_caja add constraint FKgp2ggle9pr9fbphg3acfhh2dy foreign key (id_caja) references caja (id);
alter table movimientos_caja add constraint FKq6p24j6nsky3mrdsx3h1cg96c foreign key (id_compra) references compras (id);
alter table movimientos_caja add constraint FKlqsh77mc9fttu2gv7c0fj94q7 foreign key (id_factura) references facturas (id);
alter table movimientos_caja add constraint FKgg5hupo8fx8run98bgv1vll1u foreign key (id_usuario) references usuarios (id);
alter table movimientos_caja add constraint FKfbwwbwirle698wn2ruo1csw74 foreign key (id_venta) references ventas (id);
alter table usuarios add constraint FK_USUARIO_PERMISO foreign key (id_permiso) references permisos (id);
alter table ventas add constraint FK_VENTA_CLIENTE foreign key (id_cliente) references clientes (id);
alter table ventas add constraint FK_VENTA_USUARIO foreign key (id_usuario) references usuarios (id);
INSERT INTO `permisos` (nombre, descripcion) VALUES ('ROLE_ADMIN', 'Dueño de la empresa - Tiene menos permisos que programador'),('ROLE_OPERADOR', 'Trabajador de la empresa - Tiene algunos permisos'),('ROLE_CLIENTE', 'Usuario Registrado que realiza una compra'),('ROLE_UNLOGUED', 'Consultas algunos elementos de la pagina sin estar registrado');
INSERT INTO `usuarios` (activo, fecha_creacion, id_permiso, nomb_usu, clave, email) VALUES (1, '2024-12-01', 1, 'Osvaldo', '$2y$10$ZP7gE3toR10ffABvlsvJXOGQsHaUQPizzXpuBZj5Gkf.7mT3hFmQS', 'Osvaldo@gmail.com.ar') /*user*/;
INSERT INTO `usuarios` (activo, fecha_creacion, id_permiso, nomb_usu, clave, email) VALUES (1, '2024-12-01', 3, 'Santi', '$2y$10$Y5PE96MBydWiAVCAkf1TQu99d7NKYNPWU/HEAZGQ2l5OQu2XiPiiC', 'Santi@gmail.com.ar') /*cliente*/;
INSERT INTO `luzclaritaweb`.`productos` (`activo`, `precio`, `stock`, `id_categoria`, `descripcion`, `lnk_img`) VALUES ('1', '5000.00', '6', '2', 'Torta Spiderman', 'https://donolli.com.ar/wp-content/uploads/2023/01/20221015_122724-scaled.jpg');
INSERT INTO `luzclaritaweb`.`productos` (`activo`, `precio`, `stock`, `id_categoria`, `descripcion`, `lnk_img`) VALUES ('1', '6840.00', '10', '1', 'Torta chocolate', 'https://i.ytimg.com/vi/H7uMpjzyaTU/maxresdefault.jpg');
INSERT INTO `luzclaritaweb`.`productos` (`activo`, `precio`, `stock`, `id_categoria`, `descripcion`, `lnk_img`) VALUES ('1', '4500.00', '20', '4', 'Donas glaseadas', 'https://64.media.tumblr.com/155ba7881a89c4b5a70ad4466e8d86f5/tumblr_nuvqnoaaEe1tf311io1_1280.jpg');
INSERT INTO `luzclaritaweb`.`caja` (`saldo_final`, `saldo_inicial`, `fecha`, `id_usuario`, `estado`) VALUES ('10000.00', '10000.00', '2025-04-20 00:00:00', 1, 'ABIERTA');
INSERT INTO `luzclaritaweb`.`caja` (`saldo_final`, `saldo_inicial`, `fecha`, `id_usuario`, `estado`) VALUES ('10000.00', '10000.00', '2025-04-20 00:00:00', 2, 'CERRADA');
INSERT INTO `luzclaritaweb`.`proveedores` (`activo`, `telefono`, `contacto`, `nombre`, `email`, `direccion`) VALUES ('1', '3624242424', '3624021414', 'Franco', 'Franco@gmail.com', 'san lorenzo200');
INSERT INTO `luzclaritaweb`.`proveedores` (`activo`, `telefono`, `contacto`, `nombre`, `email`, `direccion`) VALUES ('1', '3625052244', '3624400921', 'Osval', 'Osva@gmail.com', 'Mitre 22');
INSERT INTO `luzclaritaweb`.`proveedores` (`activo`, `telefono`, `contacto`, `nombre`, `email`, `direccion`) VALUES ('1', '3684252515', '444464', 'Arcor', 'ArcorSA@gmail.com', 'bs as');
INSERT INTO `luzclaritaweb`.`proveedores` (`activo`, `telefono`, `contacto`, `nombre`, `email`, `direccion`) VALUES ('1', '3624242424', '3624021453', 'ledesma', 'LDESMa@gmail.com', 'san lorenzo200');
INSERT INTO `luzclaritaweb`.`proveedores` (`activo`, `telefono`, `contacto`, `nombre`, `email`, `direccion`) VALUES ('1', '3625052244', '3624503248', 'milka', 'MilkaS.A.@gmail.com', 'Mitre 22');
INSERT INTO `luzclaritaweb`.`proveedores` (`activo`, `telefono`, `contacto`, `nombre`, `email`, `direccion`) VALUES ('1', '3684252515', '444345', 'nestle', 'NestleSA@gmail.com', 'bs as');
INSERT INTO `luzclaritaweb`.`compras` (`activo`, `fecha_hora`, `id_caja`, `id_proveedor`, `id_usuario`, `descripcion`) VALUES ('1', '2025-05-14 00:00:00', 1, 1, 1, 'levadura');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2000.00', '2024-09-14', '2026-08-21', 1, 1, 'azucar', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2000', '2024-09-14', '2026-08-21', 1, 1, 'azucar', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '15', '1500', '2025-09-20', '2024-01-16', 2, 2, 'harina', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '10', '1200', '2025-04-10', '2026-03-15', 1, 1, 'sal', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2500', '2024-09-14', '2026-08-21', 1, 1, 'azucar impalpable', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '15', '3500', '2025-09-20', '2024-01-16', 2, 2, 'levadura', 'gr');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '10', '5200', '2025-04-10', '2026-03-15', 1, 1, 'chocolate barra', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2000', '2024-09-14', '2026-08-21', 1, 1, 'huevos', 'doc');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '15', '6500', '2025-09-20', '2024-01-16', 2, 2, 'dulce de leche', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '10', '3200', '2025-04-10', '2026-03-15', 1, 1, 'durazno', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2000', '2024-09-14', '2026-08-21', 1, 1, 'azucar', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '15', '1500', '2025-09-20', '2024-01-16', 2, 2, 'harina', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '10', '1200', '2025-04-10', '2026-03-15', 1, 1, 'sal', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2000', '2024-09-14', '2026-08-21', 1, 1, 'azucar impalpable', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '15', '1500', '2025-09-20', '2024-01-16', 2, 2, 'levadura', 'gr');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '10', '1200', '2025-04-10', '2026-03-15', 1, 1, 'chocolate barra', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '145', '2000', '2024-09-14', '2026-08-21', 1, 1, 'huevos', 'doc');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '15', '1500', '2025-09-20', '2024-01-16', 2, 2, 'dulce de leche', 'kg');
INSERT INTO `luzclaritaweb`.`inventario` (`activo`, `cantidad`, `precio`, `fecha_ingreso`, `fecha_vencimiento`, `id_proveedor`, `id_usuario`, `nombre_Ingrediente`, `unidad_Medida`) VALUES ('1', '10', '1200', '2025-04-10', '2026-03-15', 1, 1, 'durazno', 'kg');
